provider:
  name: openfaas
  gateway: http://35.239.64.218:8080
functions:
  powercli-reconfigure:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powercli-vm-config-change-slack:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - vc-slack-config
    annotations:
      topic: "com/vmware/vcloud/event/task/complete"
