version: 1.0
provider:
  name: openfaas
  gateway: http://35.239.64.218:8080
functions:
  veba-echo:
    lang: python
    handler: ./handler
    image: vmware/veba-python-echo:latest
    environment:
      write_debug: true
      read_debug: true
    annotations:
      topic: "com/vmware/vcloud/event/session/login"
