version: 1.0
provider:
  name: openfaas
  gateway: http://35.239.64.218:8080
functions:
  restpost-fn:
    lang: python3
    handler: ./handler
    image: vmware/veba-python-restpost:latest
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      insecure_ssl: true
    secrets:
      - metaconfig
    annotations:
      topic: "com/vmware/vcloud/event/vm/change_state"